SELECT 
	GROUP_BY_VALUE AS PART_I_D,
	PREDICTION_1_VALUE AS FORECAST_VALUE_1m,
	PREDICTION_2_VALUE AS FORECAST_VALUE_2m,
	PREDICTION_3_VALUE AS FORECAST_VALUE_3m
FROM 
	PTE.PA_FORECAST_VALIDATION
WHERE 
	GROUP_BY_VALUE IN ('111776')